### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by ImYenil** [MherZaqaryan/BedWars1058-Private-Games#62]
**Describe the bug**
This is a bug in which the player's inventory items are kept when the player dies after changing the respawn time in a private game.

**How to reproduce**
1. Change the respawn time
2. start game and die 
3. now happen

**Screenshots**
Viedo
https://www.youtube.com/watch?v=DYfURC80rms

**Server Information (Important):**
 - Operating System: [e.g. Linux, Windows, Mac] Windows
 - Server Software: [e.g. Paper, Spigot] Paper
 - Java Version: [e.g 8, 16, 17] 11
 - Software Version: [e.g. 1.8.8] 1.8.9
 - Private Games Version: [e.g. 1.1.7] 1.1.10
 - BedWars1058 Version: [e.g. 22.2] 23.3-SNAPSHOT
 - BedWars1058 Server Type: [e.g. MULTIARENA, BUNGEE, SHARED] MULTIARENA

**Comment by MherZaqaryan** [comment]
Thanks for reporting the issue, Even tho I was pretty sure Private Games doesn't handle anything similar to `keep inventory` feature, I've tried to reproduce this issue as you show in the video, but eventually failed, everything works fine on my side. One thing I can suggest is to check if you have left any game rules for the world. This issue is invalid.
